/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shilo' at '4/07/18 10:02 AM' with Gradle 2.14.1
 *
 * @author shilo, @date 4/07/18 10:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
